config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/sobre', to: 'pages#sobre'
  get '/contato', to: 'pages#contato'
  get '/msg-lab', to: 'pages#msglab'
  get 'turmas', to: 'pages#turmas'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def sobre
  end

  def contato
  end

  def msglab
  end

  def turmas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <script src= "https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= render 'shared/form' %>
  </body>
</html>

app/views/pages/contato.html.erb
<div>
  <div class="banner-about">
    <%= image_tag("contato.png", class: "banner-sobre") %>
  </div>

  <div class="container contact-info" style='margin-top: 120px; margin-bottom: 120px'>
    <div class="row">
      <div class="col col-contato">
        <h4 style='text-align: center;'>Contato</h4>
        <p style='text-align: center;'>Whatsapp +55 21 98355-1120 </p>
      </div>
      <div class="col col-contato">
        <h4 style='text-align: center;'>Horário</h4>
        <p style='text-align: center;'>De segunda à sexta-feira</p>
        <p style='text-align: center;'>De 09h às 19h</p>
      </div>
      <div class="col col-contato-dois pl-5">
        <h4 style='text-align: center;'>Endereço</h4>
        <p style='text-align: center;'>Ladeira da Glória, 26 - Nex Coworking Bloco 3</p>
        <p style='text-align: center;'>Rio de Janeiro, RJ, 22211-120, Brasil</p>
      </div>
    </div>
  </div>

  <div class="container map-container col-md-12" style='margin-top: 180px; margin-bottom: 120px; text-align: center; margin-left: 5vh;'>
    <div class="row">
      <div class="col col-xs-12 col-md-6">
        <%= image_tag("map.png", class: "map-contato") %>
      </div>
      <div class="col col-xs-12 col-md-6 d-flex form-contato">
        <form action="https://formspree.io/f/mgepnwaq" method="POST" style="font-family: 'Oswald'">
          <h4 style="text-align: center; font-family: 'Oswald';">Fale com a gente!</h4>
          <label  style="margin-top: 20px; margin-right: 4vh;"> Seu email: <br>
            <input type="text" name="_replyto" style="width: 30vh">
          </label>
          <label  style="margin-top: 20px;"> Nome completo: <br>
            <input type="text" name="name" style="width: 30vh">
          </label>
          <label style="margin-top: 20px"> Mensagem: <br>
            <textarea name="message" style="width: 64vh; height: 15vh;"></textarea>
          </label><br>
          <button type="submit" class="btn" style="background-color: #c73858; color: white; width: 10vh">Send</button>
        </form>
      </div>
    </div>
  </div>
</div>


<!--   <div class="container-contact col-md-12 text-center">
    <div class="perguntas-frequentes col-md-12">
      <h1 class="pb-3">Perguntas Frequentes</h1>

      <div class="row no-gutters contato">
        <div class="col-xs-12 col-md-6">
          <div class="">
            <h4 class="mt-4">O MULHERES DO SUL GLOBAL É UMA ONG?</h4>
            <p align="justify">Não! Somos um negócio social, ou seja, temos como missão desenvolver
            e/ou transformar socialmente nossa realidade, gerando impacto positivo
            na vida das mulheres que empregamos. Buscamos incluir essas mulheres na
            cadeia produtiva de valor, fornecendo uma renda fixa mensal para que possam
            viver com dignidade e segurança. Buscamos um modelo de negócio auto-sustentável
            que possibilite a existência e expansão das nossas atividades.</p>
          </div>
        </div>

        <div class="col-xs-12 col-md-6">
            <h4 class="mt-4">POR QUE O NOME “MULHERES DO SUL GLOBAL”?</h4>
            <p align="justify">A primeira parte é a mais simples de entender. Nosso foco são as mulheres,
              especificamente mulheres em situação de refúgio na cidade do Rio de Janeiro.
              Já o “Sul Global”, é o que define nosso ponto de partida pra pensar em mudança
              social. Este termo é muito utilizado em estudos de Relações Internacionais e
              se refere ao conjunto de países em desenvolvimento, em sua maioria localizados
               no hemisfério sul do globo terrestre.
            </p>
        </div>
      </div>

      <div class="row no-gutters contato">
        <div class="col-xs-12 col-md-6">
          <div class="">
            <h4 class="mt-4">ONDE POSSO ENCONTRAR OS PRODUTOS?</h4>
            <p align="justify">A melhor maneira de nos ajudar é prestigiando o trabalho de nossas costureiras.
             A venda dos produtos é o que possibilita a manutenção das nossas operações.</p>
          </div>
        </div>

        <div class="col-xs-12 col-md-6">
            <h4 class="mt-4">COMO POSSO AJUDAR?</h4>
            <p align="justify">A melhor maneira de nos ajudar é prestigiando o trabalho de nossas costureiras.
             A venda dos produtos é o que possibilita a manutenção das nossas operações.</p>
            </p>
        </div>
      </div>

      <div class="row no-gutters contato">
        <div class="col-xs-12 col-md-6">
          <div class="">
            <h4 class="mt-4">ESTE PROJETO BUSCA SOLUCIONAR QUAL PROBLEMA?</h4>
            <p align="justify">Ser um negócio social de empoderamento econômico de mulheres com talento em costura,
              inseridas em contextos de refúgio e vulnerabilidade social, por meio da promoção do empreendedorismo,
              capacitação de habilidades, criação e venda de peças de costura comprometidos com os novos paradigmas
              de se fazer e consumir sustentável. </p>
          </div>
        </div>

        <div class="col-xs-12 col-md-6">
            <h4 class="mt-4">QUAL A SOLUÇAO PROPOSTA?</h4>
            <p align="justify">Promover capacitação, máquinas de costura para trabalhar de casa e desenvolvimento de
            uma rede de trabalho de criação, produção, venda e prospeção de encomendas, com geração de renda para quem
            produz e para a sustentação do projeto enquanto negócio social. Ao fortalecer jornadas empreendedoras
            colaborativas e ao mesmo tempo autônomas, promovemos um desenho de trabalho voltado para as novas economias,
            mostrando outros caminhos além do mercado tradicional. </p>
            </p>
        </div>
      </div>

    </div>
  </div>
</div> -->







<!--       <h4 class="mt-4">O MULHERES DO SUL GLOBAL É UMA ONG?</h4>
      <p align="justify">Não! Somos um negócio social, ou seja, temos como missão desenvolver
      e/ou transformar socialmente nossa realidade, gerando impacto positivo
      na vida das mulheres que empregamos. Buscamos incluir essas mulheres na
      cadeia produtiva de valor, fornecendo uma renda fixa mensal para que possam
      viver com dignidade e segurança. Buscamos um modelo de negócio auto-sustentável
      que possibilite a existência e expansão das nossas atividades.</p>
      <h4 class="mt-4">POR QUE O NOME “MULHERES DO SUL GLOBAL”?</h4>
      <p align="justify">A primeira parte é a mais simples de entender. Nosso foco são as mulheres,
        especificamente mulheres em situação de refúgio na cidade do Rio de Janeiro.
        Já o “Sul Global”, é o que define nosso ponto de partida pra pensar em mudança
        social. Este termo é muito utilizado em estudos de Relações Internacionais e
        se refere ao conjunto de países em desenvolvimento, em sua maioria localizados
         no hemisfério sul do globo terrestre.
      </p>
      <h4 class="mt-4">COMO POSSO AJUDAR?</h4>
      <p align="justify">A melhor maneira de nos ajudar é prestigiando o trabalho de nossas costureiras.
       A venda dos produtos é o que possibilita a manutenção das nossas operações.</p>
      <h4 class="mt-4">ONDE POSSO ENCONTRAR OS PRODUTOS?</h4>
      <p align="justify" class="mb-5">Nossos produtos podem ser adquiridos pessoalmente ou através de nossas redes
        sociais. Além do nosso showroom localizado na Ladeira da Glória 26, estamos
        frequentemente presentes em feiras e eventos que são previamente divulgados
        em nossa página.</p>
    </div>
  </div> -->

<!--       <script src="https://formspree.io/js/formbutton-v1.min.js" defer></script>
      <script>
        window.formbutton=window.formbutton||function(){(formbutton.q=formbutton.q||[]).push(arguments)};
        formbutton("create", {
          styles: {fontFamily:'"Oswald", sans-serif', description: {background: "#c73858"}, button: {background: "#c73858"}, title: {background: "#c73858", letterSpacing: "0.05em", textTransform: "uppercase"}},
          title: "Fala com a gente!",
          description: "A gente irá te retornar em breve.",
          action: "https://formspree.io/f/mdopejwy",
          fields: [
          {name: "name", type: "text", label: "Nome completo", required: true,},
          {name: "email", type: "email", label: "Seu email", required: true},
          {name: "Message", label: "Mensagem", type: "textarea"},
          {type: "submit"}
          ],
        });
      </script> -->

app/views/pages/home.html.erb
<!-- CAROUSEL -->

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= link_to sobre_path do %>
        <%= image_tag("carousel-one.png", class: "d-block w-100") %>
      <% end %>
    </div>

    <div class="carousel-item">
      <%= link_to msg_lab_path do %>
        <%= image_tag("carousel-two.png", class: "d-block w-100") %>
      <% end %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!-- BANNER ONE -->

<div class="banner-one">
  <div class="header-one">
    <div class="col-12 col-md-6">
      <h1><b>Queremos empoderar e transformar a vida de mulheres refugiadas</b></h1>
    </div>
  </div>
</div>

<!-- BANNER TWO -->

<div class="row no-gutters">
  <div class="col-xs-12 col-md-6">
    <div class="image-two">
      <%= image_tag("banner-two.jpg")%>
    </div>
  </div>

  <div class="col-xs-12 col-md-6">
    <div class="banner-two">
      <div class="paragraph-two row justify-content-center">
        <div class="col-10 col-md-8">
          <h6>
            Somos um negócio social de empoderamento econômico de talentosas mulheres costureiras 
            inseridas em contextos de refúgio e vulnerabilidade social, baseado na promoção do empreendedorismo, 
            capacitação de habilidades, criação e venda de peças têxteis comprometidas com os novos paradigmas 
            de se fazer e consumir sustentável.
          </h6>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- BANNER THREE -->

<div class="row no-gutters">
  <div class="col-xs-12 col-md-6">
    <div class="banner-three">
      <div class="paragraph-three row justify-content-center">
        <div class="col-10 col-md-8">
          <h6>
            Promovemos o treinamento em costura de atelier, disponibilizamos maquinário para trabalhar de casa, 
            buscamos promover o empreendedorismo com a formalização de costureiras micro-empreendedoras, 
            e as conectamos com o mercado.
          </h6>
        </div>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-md-6">
    <div class="image-three">
      <%= image_tag("banner-three.jpg")%>
    </div>
  </div>
</div>

<!-- BANNER FOUR -->

<div class="row no-gutters">
  <div class="col-xs-12 col-md-6">
    <div class="image-four">
      <%= image_tag("banner-four.jpg")%>
    </div>
  </div>
  <div class="col-xs-12 col-md-6">
    <div class="banner-four">
      <div class="paragraph-four row justify-content-center">
        <div class="col-10 col-md-8">
          <h6>
            Nossos valores são regidos pela <b>tolerância</b>, <b>empatia</b>, <b>responsabilidade social</b>, 
            <b>compromisso coletivo</b>, <b>independência</b>, <b>ética</b> e <b>transparência</b>.
          </h6>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- BANNER FIVE -->

<div class="banner-five">
  <div class="header-five">
    <div>
      <div>
        <h1 class="mb-4"><b>MSG LAB</b></h1>
      </div>
      <div>
        <p>
          MSG LAB é um laboratório de aprendizagem e profissionalização dedicado à mulheres
          iniciantes ou com habilidades de costura.
          <br>
          <br>
          Nosso programa é projetado para que as mulheres dominem as habilidades essenciais para trabalhar 
          como uma costureira industrial.
          <br>
          <br>
          Com aulas práticas, de forma a contribuir para a integração econômica sustentável,
          as alunas aprendem fazendo e desenvolvem as habilidades iniciais necessárias para se tornarem
          microempreendedores ou profissionais da área têxtil.
        </p>
      </div>
      <div class="text-center mt-5">
        <%= link_to "/msg-lab" do %>
          <p class="btn m-2">CONHEÇA O PROGRAMA</p>
        <% end %>

        <%= link_to "/turmas" do %>
          <p class="btn m-2">CONHEÇA AS TURMAS</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- BANNER SIX -->

<div class="banner-six">
  <div class="header-six">
    <div class="col-12 col-md-6">
      <h1><b>Cada vale-presente vale o presente e o futuro das Mulheres do Sul Global</b></h1>
    </div>
  </div>
</div>

<!-- BANNER SEVEN -->

<div class="banner-seven">
  <div class="video">
    <iframe src="https://drive.google.com/file/d/1vZyoo80XLioF19wx5KZS4-TfdKCbjWv2/preview" allowfullscreen></iframe>
  </div>
  <p>Assista ao vídeo da nossa fundadora, Manu, contando mais sobre o projeto e a ação de Natal.</p>

  <div class="text-center mt-5 mb-3">
    <%= link_to "/" do %>
      <p class="btn m-2">ACESSE A LOJA</p>
    <% end %>
  </div>
</div>

<!-- BANNER EIGHT -->

<div class="banner-eight">
  <div class="cards">
    <%= link_to "/sobre" do %>
      <div class="card-one m-3"><h5>NOSSA HISTÓRIA</h5></div>
    <% end %>
    
    <%= link_to "http://www.msgloja.com/", target: "_blank" do %>
      <div class="card-two m-3"><h5>NOSSA LOJA</h5></div>
    <% end %>
    
    <%= link_to "/msg-lab" do %>
      <div class="card-three m-3"><h5>MSG LAB</h5></div>
    <% end %>
    
    <%= link_to "/contato" do %>
      <div class="card-four m-3"><h5>CONTRIBUA</h5></div>
    <% end %>
  </div>
</div>

app/views/pages/msglab.html.erb
<div class="banner-about">
  <%= image_tag("msglab.png", class: "banner-sobre") %>
</div>

<div class="container msg-lab">
  <div class="col-sm-12 col-md-12 six-column">
    <div class="investidores">
      <h2>Investidores</h2>

     <%= image_tag("investidores.png")%>
    </div>

    <hr>

    <div>
      <h2>Sobre o MSG Lab</h2>
      <h5 class="text-primary">Programa de 3 semanas, com até 140 horas de iniciação à costura industrial e desenvolvimento profissional.</h5>
    </div>

    <div>
      <p>
        <b>
          O MSG Lab é um laboratório de aprendizagem e profissionalização para o segmento têxtil, 
          dedicado a ampliar a integração econômica das mulheres migrantes a partir de um olhar para as questões de gênero e o Sul Global.
        </b>
      </p>

      <p>
        Nosso programa é desenhado para que mulheres dominem as habilidades essenciais para trabalhar como Costureira Industrial. 
        Com aulas práticas, a fim de contribuir para integração econômica sustentável, as alunas aprendem fazendo, e desenvolvem as 
        competências iniciais necessárias para se tornarem micro-empreendedoras ou profissionais na área têxtil.
      </p>
    </div>

    <div>
      <p><b>Nosso currículo tem dois componentes complementares:</b></p>

      <ul>
        <li>Instrução a função de costureira auxiliar industrial e outras áreas dentro da linha de produção têxtil como acabamento, arremate e passadoria;</li>
        <li>Workshops de desenvolvimento profissional e preparação para a carreira para garantir o sucesso de longo prazo, independência e adaptação ao mercado de trabalho brasileiro.</li>
      </ul>
    </div>

    <div>
      <p><b>Em 3 semanas, nós cobrimos:</b></p>

      <ul>
        <li>Formar operadoras de maquinário  industrial, contribuindo assim  para uma formação direcionada dentro do universo têxtil;</li>
        <li>Desenvolvimento de 6  projetos  que  envolvem diferentes modelos com distintas técnicas de acabamentos;</li>
        <li>Treinamento sobre mercado de trabalho brasileiro, avaliação das competências socioemocionais, elaboração de currículo e plano de carreira;</li>
        <li>Introdução às oportunidades profissionais no microempreendedorismo e na indústria criativa brasileira;</li>
        <li>Treinamento em oratória, networking e branding pessoal.</li>
      </ul>
    </div>

    <hr>

    <div>
      <p><b>Números de Impacto</b></p>

      <ul>
        <li>8 Programas MSG Lab foram lançados de 2017 - 2020;</li>
        <li>110 participantes do MSG Lab;</li>
        <li>20 das participantes integram o núcleo duro da fábrica Mulheres do Sul Global após o programa.</li>
      </ul>

      <i>REF: <a href="https://makersunite.eu/creative-lab/" target="_blank">https://makersunite.eu/creative-lab/</a></i>

      <ul>
        <li>8  Programas MSG Lab Oportunidades programados para 2021;</li>
        <li>160 participantes;</li>
        <li>40 participantes a serem conectadas  para oportunidade profissional após o programa.</li>
      </ul>
    </div>
  </div>

  <hr>

  <div class="col-sm-12 col-md-12 six-column">
    <div>
      <h2 class="mt-5">Metodologia</h2>
    </div>

    <div>
      <p>
        Depois de executar 8 programas bem-sucedidos, desenvolvemos a formação baseada no modelo de <b>aprendizagem experiencial</b> <i>learning by doing/aprender fazendo</i>, 
        que combina teoria e prática, com base nesses 3 pilares.
      </p>

      <ul>
        <li>Qualificação Técnica em Costura Industrial;</li>
        <li>Desenvolvimento Sócio Emocional;</li>
        <li>Desenvolvimento Profissional.</li>
      </ul>
    </div>

    <hr>

    <div>
      <p><a href="#como-funciona">1. Como funciona</a></p>
      <p><a href="#curriculo-do-programa">2. Currículo do programa</a></p>
      <p><a href="#quem-deve-aplicar">3. Quem deve aplicar</a></p>
      <p><a href="#duracao-e-investimento">4. Duração e investimento</a></p>
      <p><a href="#inscreva-se">5. Inscreva-se</a></p>
    </div>

    <hr>

    <div id="como-funciona">
      <h2>1. Como funciona</h2>

      <p>
        O Lab Aprendizagem é realizado na nossa fábrica, que conta com infraestrutura industrial para atender ao perfil de produção em escala. 
        As situações de aprendizagem consideram a realidade da profissão de Costureira em seu local de trabalho, identificando os elementos relativos 
        ao trabalho a ser executado, bem como os cuidados básicos de conservação dos equipamentos. 
      </p>

      <p>
        As Mentoras do Lab Desenvolvimento Pessoal e Profissional fornecem feedback sobre currículo e avaliação dedicada em todos os exercícios dentro do programa. 
        O participante recebe apoio individual das mentoras para desenvolver ainda mais seu plano de carreira. Depois de atingir os marcos necessários, 
        as participantes são conectadas à sua próxima etapa profissional, permitindo-lhes trabalhar no Brasil de forma independente e trabalhar conosco em atribuições 
        criativas para nossos parceiros.
      </p>
    </div>

    <hr>

    <div id="curriculo-do-programa">
      <h2>2. Currículo do programa</h2>

      <div class="mb-5">
        <p>
          <b>Lab aprendizagem 1 -</b> Tem como foco introdução ao maquinário industrial, a formação de operadoras de máquinas de costura industrial, direcionado 
          para técnicas de produção em escala.
        </p>

        <p class="m-0"><i>Perfil: Iniciantes</i></p>
        <p class="m-0"><i>Carga horária: 96 horas</i></p>
      </div>

      <div class="mb-5">
        <p>
          <b>Lab aprendizagem 2 -</b> Dando continuidade ao <b>Lab 1</b>, aqui as alunas aprofundam nas principais práticas e técnicas utilizadas na costura industrial 
          da confecção, noções de manutenção, normas, e a relação destes conteúdos com a produtividade na costura e a qualidade do produto final.
        </p>

        <p class="m-0"><i>Perfil: Iniciantes</i></p>
        <p class="m-0"><i>Carga horária: 40 horas</i></p>
      </div>

      <div class="mb-5">
        <p>
          <b>Lab  profissionalização -</b> Módulos transversais, onde cada curso se concentra em uma habilidade específica.
          Ex: Especialização de bolsas e acessórios, Conserto de roupas - (96h cada módulo). Essa é uma etapa dedicada às alunas que passaram por nossos laboratórios de 
          aprendizagem 1 e 2, ou profissionais que já chegam no programa com experiência na área. Nesta fase, focamos num aperfeiçoamento direcionado a confecção de bolsas 
          e acessórios, aprendendo na prática como funciona o processo industrial em todas as suas etapas de produção. O laboratório tem como objetivo afinar profissionais 
          em maquinários específicos para este nicho, e revelar profissionais em outras etapas de 
          produção para além da costura (ex. oficial de mesa, etc).
        </p>

        <p class="m-0"><i>Perfil: Iniciantes que tenham cursado o Lab 1 e 2, ou costureiras com experiência</i></p>
        <p class="m-0"><i>Carga horária: 80 horas</i></p>
      </div>

      <div class="mb-5">
        <p>
          <b>Lab  empreendedorismo -</b> A proposta do Lab empreendedorismo é oferecer  uma visão global para quem deseja empreender o seu próprio negócio de costura ou 
          ainda trabalhar em confecções. A ideia é promover ferramentas contextualizadas com os desafios do mercado atual. Formar uma profissional crítica e competente, 
          atuando com foco em resultados e na prestação de serviços com qualidade e sustentabilidade.
        </p>

        <p class="m-0"><i>Oficinas: Estratégias de precificação dos produtos; Controle de estoque, Gestão de resíduos; Atendimento de excelência, Vendas online, etc</i></p>
        <p class="m-0"><i>Perfil: Iniciantes e profissionais que fazem parte do nosso programa</i></p>
        <p class="m-0"><i>Carga horária: 40 horas (aprox. 2 semanas/intensivo)</i></p>
      </div>
    </div>

    <hr>

    <div id="quem-deve-aplicar">
      <h2>3. Quem deve aplicar</h2>

      <ul>
        <li>Refugiados, asilados ou sobreviventes do tráfico de pessoas com idades entre 18 e 65 anos;</i>
        <li>Chegou ao Brasil nos últimos 3 anos;</li>
        <%# <li>xx sobre documentos protocolo e RNM;</li> %>
        <li>Disposto a sentar na máquina de costura  por 8 horas;</li>
        <li>Capaz de seguir instruções e se comunicar em português intermediário;</li>
        <li>Disponibilidade  das 9h às 17h, de segunda à sexta por 3 semanas;</li>
        <li>Apaixonado por costura e interessada em seguir carreira na indústria criativa.</li>
      </ul>
    </div>

    <hr>

    <div id="duracao-e-investimento">
      <h2>4. Duração e investimentos</h2>

      <p>Nosso programa é gratuito e tem duração de 03 semanas com até 140 horas.</p>
    </div>
  </div>

  <div id="inscreva-se" class="text-center mt-5 mb-5">
    <a href="https://chat.whatsapp.com/K4lPQYke1PQ9zm5Kq7FPKT" target="_blank" class="btn">Inscreva-se</a>
  </div>
</div>

app/views/shared/_form.html.erb
<script src="https://formspree.io/js/formbutton-v1.min.js" defer></script>
<script>
  window.formbutton=window.formbutton||function(){(formbutton.q=formbutton.q||[]).push(arguments)};
  formbutton("create", {
    styles: {fontFamily:'"Poppins", sans-serif', description: {background: "#C50058"}, button: {background: "#C50058"}, title: {background: "#C50058", letterSpacing: "0.05em", textTransform: "uppercase"}},
    title: "Fale com a gente!",
    description: "Iremos te retornar em breve.",
    action: "https://formspree.io/f/mgepnwaq",
    fields: [
    {name: "name", type: "text", label: "Nome completo", required: true,},
    {name: "email", type: "email", label: "Seu email", required: true},
    {name: "Message", label: "Mensagem", type: "textarea"},
    {type: "submit"}
    ],
  });
</script>